# Generated by Django 5.1.2 on 2025-06-01 03:03

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('about', 'About Us'), ('mission', 'Our Mission'), ('vision', 'Our Vision'), ('goals', 'Our Goals')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='about_sections/')),
                ('heading', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
    ]
