# Generated by Django 5.1.2 on 2025-06-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0002_aboutsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
