# Generated by Django 5.1.2 on 2025-06-01 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0003_delete_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Website Details', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Details',
            },
        ),
        migrations.AddField(
            model_name='aboutus',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_us', to='websitedashboard.details'),
        ),
        migrations.AddField(
            model_name='ourgoals',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_goals', to='websitedashboard.details'),
        ),
        migrations.AddField(
            model_name='ourmission',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_mission', to='websitedashboard.details'),
        ),
        migrations.AddField(
            model_name='ourvision',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_vision', to='websitedashboard.details'),
        ),
    ]
