# Generated by Django 5.1.2 on 2025-06-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0008_remove_visa_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
