# Generated by Django 5.1.2 on 2025-06-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0009_visa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='slug',
        ),
    ]
