# Generated by Django 5.1.2 on 2025-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0010_remove_visa_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
