# Generated by Django 5.1.2 on 2025-06-04 04:40

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0011_visa_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Website Home Page', max_length=200)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='AboutUshome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us/')),
                ('heading', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_us', to='websitedashboard.home')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='OurGoalshome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_goals/')),
                ('heading', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_goals', to='websitedashboard.home')),
            ],
            options={
                'verbose_name_plural': 'Our Goals',
            },
        ),
        migrations.CreateModel(
            name='OurMissionhome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_mission/')),
                ('heading', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_mission', to='websitedashboard.home')),
            ],
            options={
                'verbose_name_plural': 'Our Mission',
            },
        ),
        migrations.CreateModel(
            name='OurVisionhome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_vision/')),
                ('heading', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Our_vision', to='websitedashboard.home')),
            ],
            options={
                'verbose_name_plural': 'Our Vision',
            },
        ),
    ]
