# Generated by Django 5.1.2 on 2025-06-05 05:01

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0012_home_aboutushome_ourgoalshome_ourmissionhome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='faqshome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='websitedashboard.home')),
            ],
            options={
                'verbose_name_plural': "FAQ's",
            },
        ),
    ]
