# Generated by Django 5.1.2 on 2025-06-05 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0014_highlightshome'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightshome',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='websitedashboard.home'),
        ),
    ]
