# Generated by Django 5.1.2 on 2025-06-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0015_highlightshome_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightshome',
            name='mainheading',
            field=models.CharField(default=' ', max_length=200, verbose_name='Main Heading'),
        ),
        migrations.AlterField(
            model_name='highlightshome',
            name='heading',
            field=models.CharField(max_length=200, verbose_name='Heading'),
        ),
    ]
