# Generated by Django 5.1.2 on 2025-06-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0016_highlightshome_mainheading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightshome',
            name='mainheading',
            field=models.CharField(default='', max_length=200, verbose_name='Main Heading'),
        ),
    ]
