# Generated by Django 5.1.2 on 2025-06-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0017_alter_highlightshome_mainheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightshome',
            name='mainheading',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Main Heading'),
        ),
    ]
