# Generated by Django 5.1.2 on 2025-06-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0018_alter_highlightshome_mainheading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightshome',
            name='description',
        ),
        migrations.RemoveField(
            model_name='highlightshome',
            name='mainheading',
        ),
        migrations.AddField(
            model_name='highlightshome',
            name='number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='highlightshome',
            name='heading',
            field=models.CharField(default='', max_length=300),
        ),
    ]
