# Generated by Django 5.1.2 on 2025-06-07 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0020_bookingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='passport_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
