# Generated by Django 5.1.2 on 2025-06-10 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0023_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='websitedashboard.bookingdetail'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(upload_to='payment_proofs/'),
        ),
    ]
