# Generated by Django 5.1.2 on 2025-06-11 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0025_bookingdetail_user_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='websitedashboard.bookingdetail'),
        ),
    ]
