# Generated by Django 5.1.2 on 2025-06-11 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0026_remove_bookingdetail_user_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Under Process', 'Under Process'), ('Accepted', 'Accepted'), ('Received', 'Received')], default='Under Process', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='websitedashboard.bookingdetail'),
        ),
    ]
