# Generated by Django 5.1.2 on 2025-06-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0027_payment_payment_status_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Under Process', 'Under Process'), ('Accepted', 'Accepted'), ('Received', "Didn't Receive Payment")], default='Under Process', max_length=20),
        ),
    ]
