# Generated by Django 5.1.2 on 2025-06-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0028_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Under Process', 'Under Process'), ('Accepted', 'Accepted'), ('not_received', 'Payment Not Received')], default='Under Process', max_length=20),
        ),
    ]
