# Generated by Django 5.1.2 on 2025-06-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0030_visitor_alter_payment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.DeleteModel(
            name='BookingDetail',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
