# Generated by Django 5.1.2 on 2025-06-16 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='appointment_location',
            field=models.CharField(choices=[('pan-india', 'Pan India - Biometrics and Interview'), ('mumbai', 'Mumbai - Biometrics and Interview')], default='pan-india', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='travellers',
            field=models.PositiveIntegerField(default=1, help_text='Number of travellers (minimum 1)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
