# Generated by Django 5.1.2 on 2025-06-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_bookingdetail_appointment_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='appointment_location',
            field=models.CharField(choices=[('pan-india', 'Pan India - Biometrics and Interview'), ('mumbai', 'Mumbai - Biometrics and Interview')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='travellers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
