# Generated by Django 5.1.2 on 2025-06-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_payment_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingdetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking Detail', 'verbose_name_plural': 'Booking Details'},
        ),
    ]
