# Generated by Django 5.1.2 on 2025-06-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_alter_bookingdetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingdetail',
            options={'verbose_name': 'Booking Detail', 'verbose_name_plural': 'Booking Details'},
        ),
    ]
