# Generated by Django 5.1.2 on 2025-06-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0007_alter_bookingdetail_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
    ]
