# Generated by Django 5.1.2 on 2025-06-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0009_payment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='security_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='usavisa_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='usavisa_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
